In [105]:
%matplotlib
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import pandas as pd
from PIL import Image
from scipy import ndimage
from scipy import misc

from sklearn.datasets import fetch_mldata
from sklearn.neural_network import MLPRegressor

Using matplotlib backend: MacOSX


In [2]:
IMAGE_FOLDER_PATH = "/Users/zackakil/Desktop/capture clean/"

In [3]:
image_labels = pd.Series.from_csv('rugby_image_labels.csv')
image_labels = image_labels.dropna()

In [4]:
image_labels.keys()[0]

'1489359202.14.jpg'

In [5]:
output = {}

face = misc.imread(IMAGE_FOLDER_PATH+image_labels.keys()[0], flatten=True)
face1 = misc.imread(IMAGE_FOLDER_PATH+image_labels.keys()[1], flatten=True)     
plt.imshow((face[200:300] - face1[200:300])>30)
plt.show()

In [6]:
UPPER_FRAME = 300
LOWER_FRAME = 200
THRESHOLD = 30
def comapare_frames(frame_1_file_name, frame_2_file_name):
    f1 = misc.imread(frame_1_file_name, flatten=True)
    f2 = misc.imread(frame_2_file_name, flatten=True)
    diff = (f1[LOWER_FRAME:UPPER_FRAME] - f2[LOWER_FRAME:UPPER_FRAME])>THRESHOLD
    return [diff.sum(axis=0),diff]

def get_image(file_name):
    return misc.imread(file_name)

In [124]:
frame_compares_sum = []
frame_compares = []
frame_images = []
i = 0
images_to_process = image_labels[:]
for index, value in images_to_process[:-1].iteritems():
    i += 1
    curr_image = IMAGE_FOLDER_PATH + index
    next_image_index = image_labels.index.get_loc(index)+1
    next_image_key = IMAGE_FOLDER_PATH + image_labels.keys()[next_image_index]
    out = comapare_frames(curr_image, next_image_key)
    frame_compares.append(out[1])
    frame_compares_sum.append(out[0])
    frame_images.append(get_image(next_image_key))
    if not (i % 25):
        print('{0} images processed'.format(i))

25 images processed
50 images processed
75 images processed
100 images processed
125 images processed
150 images processed
175 images processed
200 images processed
225 images processed
250 images processed
275 images processed
300 images processed
325 images processed
350 images processed
375 images processed
400 images processed
425 images processed
450 images processed
475 images processed
500 images processed
525 images processed
550 images processed
575 images processed
600 images processed
625 images processed
650 images processed
675 images processed
700 images processed
725 images processed
750 images processed
775 images processed
800 images processed
825 images processed
850 images processed
875 images processed
900 images processed
925 images processed
950 images processed
975 images processed
1000 images processed
1025 images processed
1050 images processed
1075 images processed
1100 images processed
1125 images processed
1150 images processed
1175 images processed
1200 ima

In [8]:
def temporal_data(data, frames, end_to_end=True):
    '''
    Join frames of sequencial items of data together into idenvidual items.
    '''
    output = []
    
    # check if user wants frames to overlap or be end-to-end     
    if end_to_end:
        item_end_frames = frames
        len_adjust = 0
    else:
        item_end_frames = 1
        len_adjust = frames - 1

    for i in range(0, len(data) - len_adjust, item_end_frames):
        start_array = np.array([])
        for j in range(frames):
            start_array = np.concatenate((start_array, data[i+j]), axis=0)
        output.append(start_array)
    return output

In [43]:
tet = []
for i in range(20):
    tet.append(list(range(i, i+5)))
tet

[[0, 1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [2, 3, 4, 5, 6],
 [3, 4, 5, 6, 7],
 [4, 5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [6, 7, 8, 9, 10],
 [7, 8, 9, 10, 11],
 [8, 9, 10, 11, 12],
 [9, 10, 11, 12, 13],
 [10, 11, 12, 13, 14],
 [11, 12, 13, 14, 15],
 [12, 13, 14, 15, 16],
 [13, 14, 15, 16, 17],
 [14, 15, 16, 17, 18],
 [15, 16, 17, 18, 19],
 [16, 17, 18, 19, 20],
 [17, 18, 19, 20, 21],
 [18, 19, 20, 21, 22],
 [19, 20, 21, 22, 23]]

In [44]:
temporal_data(tet, 2, False)

[array([ 0.,  1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.,  5.]),
 array([ 1.,  2.,  3.,  4.,  5.,  2.,  3.,  4.,  5.,  6.]),
 array([ 2.,  3.,  4.,  5.,  6.,  3.,  4.,  5.,  6.,  7.]),
 array([ 3.,  4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.,  8.]),
 array([ 4.,  5.,  6.,  7.,  8.,  5.,  6.,  7.,  8.,  9.]),
 array([  5.,   6.,   7.,   8.,   9.,   6.,   7.,   8.,   9.,  10.]),
 array([  6.,   7.,   8.,   9.,  10.,   7.,   8.,   9.,  10.,  11.]),
 array([  7.,   8.,   9.,  10.,  11.,   8.,   9.,  10.,  11.,  12.]),
 array([  8.,   9.,  10.,  11.,  12.,   9.,  10.,  11.,  12.,  13.]),
 array([  9.,  10.,  11.,  12.,  13.,  10.,  11.,  12.,  13.,  14.]),
 array([ 10.,  11.,  12.,  13.,  14.,  11.,  12.,  13.,  14.,  15.]),
 array([ 11.,  12.,  13.,  14.,  15.,  12.,  13.,  14.,  15.,  16.]),
 array([ 12.,  13.,  14.,  15.,  16.,  13.,  14.,  15.,  16.,  17.]),
 array([ 13.,  14.,  15.,  16.,  17.,  14.,  15.,  16.,  17.,  18.]),
 array([ 14.,  15.,  16.,  17.,  18.,  15.,  16.,  17.,  18.,  19.]),


In [19]:
def bin_sum(data_array, bins):
    bin_size = int(len(data_array)/bins)
    return data_array.reshape(-1, bin_size).sum(axis=1)

In [23]:
bin_sum(frame_compares_sum[0],20)

array([11, 32, 44, 65, 70,  5, 21, 10,  0,  0,  8,  3,  9,  0,  0,  0,  0,
        0,  1,  0])

# Animated visualisation

In [45]:
fig, (ax1, ax2, ax3) = plt.subplots(3,1)

im = ax1.imshow(frame_images[0][LOWER_FRAME:UPPER_FRAME], animated=True)
im2 = ax2.imshow(frame_compares[0], animated=True)
to_plot = frame_compares_sum[10].reshape(-1, 10).sum(axis=1)
im3, = ax3.plot(to_plot)

line = [im, im2, im3]

def updatefig(i):
    line[0].set_array(frame_images[i][LOWER_FRAME:UPPER_FRAME])
    line[1].set_array(frame_compares[i])
    to_plot = frame_compares_sum[i].reshape(-1, 10).sum(axis=1)
    line[2].set_ydata(to_plot)   
    return line

ani = animation.FuncAnimation(fig, 
                              updatefig,
                              np.arange(200, 300),
                              interval=150,
                              blit=True)
plt.show()

In [52]:
ani.save('animation.gif', writer='imagemagick', fps=10)

In [29]:
plt.plot(np.histogram(frame_compares_sum[10],100)[0])

In [37]:
frame_compares_sum[0].reshape(-1, 20).sum(axis=1)

array([ 0, 18, 25, 28, 50, 22, 52, 27,  5, 21,  0, 10,  0,  0,  0,  0,  0,
        8,  3,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0])

# Assemble training data

In [157]:
# bin sums of pixel diffs
num_of_bins = 20
# normmilise by the maximum sum value (100 becuase that is teh heighht of the crop zone) 
normalise_var = 100 
binned_pixel_diffs = [bin_sum(d, num_of_bins)/normalise_var for d in frame_compares_sum]
binned_pixel_diffs[:2]

[array([ 0.11,  0.32,  0.44,  0.65,  0.7 ,  0.05,  0.21,  0.1 ,  0.  ,
         0.  ,  0.08,  0.03,  0.09,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.01,  0.  ]),
 array([ 0.  ,  0.55,  0.22,  0.85,  2.36,  1.75,  0.  ,  0.71,  0.01,
         0.  ,  0.12,  2.49,  2.35,  1.48,  0.3 ,  0.34,  0.  ,  0.01,
         0.  ,  0.  ])]

In [158]:
# temporal bundel multiple frames together into rows
num_of_frames_per_row = 2
temporaly_bundeled_data =  np.matrix(temporal_data(binned_pixel_diffs, num_of_frames_per_row, end_to_end=False))
temporaly_bundeled_data[:2]

matrix([[ 0.11,  0.32,  0.44,  0.65,  0.7 ,  0.05,  0.21,  0.1 ,  0.  ,
          0.  ,  0.08,  0.03,  0.09,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.01,  0.  ,  0.  ,  0.55,  0.22,  0.85,  2.36,  1.75,  0.  ,
          0.71,  0.01,  0.  ,  0.12,  2.49,  2.35,  1.48,  0.3 ,  0.34,
          0.  ,  0.01,  0.  ,  0.  ],
        [ 0.  ,  0.55,  0.22,  0.85,  2.36,  1.75,  0.  ,  0.71,  0.01,
          0.  ,  0.12,  2.49,  2.35,  1.48,  0.3 ,  0.34,  0.  ,  0.01,
          0.  ,  0.  ,  0.  ,  0.2 ,  0.16,  0.22,  0.59,  0.35,  0.  ,
          0.  ,  0.  ,  0.  ,  0.09,  0.03,  0.02,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ]])

In [131]:
# gather desired output to match with last frame of bundeled data
# normilsie by the maximum pixel location (640 becuassee that is the width of the frame)
normalise_var = 640
desired_output_for_frames = image_labels.values[1:-1]/normalise_var
desired_output_for_frames[:3]

array([ 0.221875 ,  0.2484375,  0.24375  ])

In [132]:
len(desired_output_for_frames), len(temporaly_bundeled_data)

(2532, 2532)

# Train neural network 

In [196]:

# mnist = fetch_mldata("MNIST original")
# rescale the data, use the traditional train/test split
X, y = temporaly_bundeled_data, desired_output_for_frames
split_boundary = 2000
X_train, X_test = X[:split_boundary], X[split_boundary:]
y_train, y_test = y[:split_boundary], y[split_boundary:]


In [211]:

train_results = []
test_results = []
layer_vals = list(range(1,20))
for i in layer_vals:
    rgr = MLPRegressor(hidden_layer_sizes=(i), max_iter=2000, alpha=5,
                        solver='lbfgs', verbose=10, tol=1e-4, random_state=1,
                        learning_rate_init=.1)

    rgr.fit(X_train, y_train)
    train_score = rgr.score(X_train, y_train)
    test_score = rgr.score(X_test, y_test)
    print("Training set score: %f" % train_score)
    print("Test set score: %f" % test_score)
    train_results.append(train_score)
    test_results.append(test_score)

Training set score: 0.571283
Test set score: 0.665764
Training set score: 0.652858
Test set score: 0.691645
Training set score: 0.724124
Test set score: 0.644970
Training set score: 0.761381
Test set score: 0.716946
Training set score: 0.775919
Test set score: 0.752608
Training set score: 0.794357
Test set score: 0.749511
Training set score: 0.805131
Test set score: 0.724045
Training set score: 0.781057
Test set score: 0.747542
Training set score: 0.806779
Test set score: 0.746304
Training set score: 0.809497
Test set score: 0.739113
Training set score: 0.826582
Test set score: 0.741138
Training set score: 0.823439
Test set score: 0.756210
Training set score: 0.817493
Test set score: 0.735698
Training set score: 0.837338
Test set score: 0.763959
Training set score: 0.843675
Test set score: 0.753280
Training set score: 0.831951
Test set score: 0.758104
Training set score: 0.834461
Test set score: 0.748013
Training set score: 0.818521
Test set score: 0.741188
Training set score: 0.839420

In [193]:
rgr = MLPRegressor(hidden_layer_sizes=(10), max_iter=2000, alpha=0.01,
                    solver='lbfgs', verbose=10, tol=1e-4, random_state=1,
                    learning_rate_init=.1)

rgr.fit(X_train, y_train)
train_score = rgr.score(X_train, y_train)
test_score = rgr.score(X_test, y_test)
print("Training set score: %f" % train_score)
print("Test set score: %f" % test_score)

Training set score: 0.858760
Test set score: 0.721966


In [212]:
plt.plot(layer_vals,train_results)
plt.plot(layer_vals,test_results)

In [214]:
o = rgr.predict(temporaly_bundeled_data)
plt.plot(o)
plt.plot(desired_output_for_frames)

## Save model

In [215]:
from sklearn.externals import joblib

In [216]:
joblib.dump(rgr, 'rugby_predictor.pkl') 

['rugby_predictor.pkl']